### ISSUE TITLE
cicada http 500 error

### ISSUE THREAD

**Issue by Emanon42** [guyujiezi/guyujiezi#4]
when try to use cicada to encrypt text, it gives `POST https://guyujiezi.com/api/encrypt 500`
Platforms: chrome 73.0.3683.103 x64

**Comment by guyujiezi** [comment]
if plaintext contains any illegal character, the service will return 500 error

the service just support "Chinese characters" and  "English alphabet"

maybe other charsets will be supported in the future. but in the first, I should find some opensource or free font

**Comment by guyujiezi** [comment]
「西城杨柳弄春柔，动离忧，泪难收」3cakhp/yaEAr。

**Comment by guyujiezi** [comment]
Oh, I found Japanese kana is also supported, maybe the plaintext contains some "emoji" characters

**Comment by guyujiezi** [comment]
#1
